include:
  - path: ./deployments/app/compose.yml
  - path: ./deployments/monitoring/compose.yml
  - path: ./deployments/kafka/compose.yml

networks:
  internal-net:
    driver: bridge
  log-net:
    driver: bridge
